apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: my-app
    image: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: my-volume
      mountPath: /app/1.csv
      subPath: 1.csv
  volumes:
  - name: my-volume
    hostPath:
    configMap:
      name: csvdata
