apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
  name: poda
spec:
  containers:
  - image: nginx
    imagePullPolicy: Never
    name: podb
    resources:
      requests:
        memory: "40Mi"
      limits:
        memory: "400Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
  name: podb
spec:
  containers:
  - image: httpd
    imagePullPolicy: Never
    name: podb
    resources:
      requests:
        memory: "40Mi"
      limits:
        memory: "200Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
  name: podc
spec:
  containers:
  - image: redis
    imagePullPolicy: Never
    name: podc
    resources:
      requests:
        memory: "40Mi"
      limits:
        memory: "400Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
